#!/bin/bash
query="$1"
doc_dir=~/docs
for d in $(ls "$doc_dir" )
do
    for f in $(ls -1 "$doc_dir/$d" | grep "$query")
    do
        filename="$doc_dir/$d/$f"
        echo $filename
        o "$filename"
    done
done
